# https://docs.travis-ci.com/user/languages/csharp/
language: csharp

# run on Ubuntu 14.04
dist: trusty

# build with .NET Core runtime
mono: none
dotnet: 2.0.0

# run build
script:
 - cd src/ProfileServer
 - dotnet restore --configfile NuGet.Config
 # create executable
 - dotnet publish --configuration Release --runtime linux-x64
 # initialize the Profile Server's database file
 - dotnet ef database update
 - cp ProfileServer.db bin/Release/netcoreapp2.0/linux-x64/ProfileServer.db
 - cd bin/Release/netcoreapp2.0/linux-x64
 # generate TLS certificate
 - openssl req -nodes -x509 -newkey rsa:4096 -subj "/C=CI/ST=CI/L=CI/O=CI/CN=CI" \-keyout ProfileServer.key -out ProfileServer.cer -days 365000
 - openssl pkcs12 -export -out ProfileServer.pfx -inkey ProfileServer.key -in ProfileServer.cer -passout pass:""
 # setup conf with public IP
 - extip=$(dig +short myip.opendns.com @resolver1.opendns.com)
 - sed -i -e "/external_server_address =/ s/= .*/= ${extip}/" ./ProfileServer.conf
 # start and validate Profile Server
 - nohup ./ProfileServer &
 - pid=$!
 # display any output captured and kill the server
 - sleep 3 && kill $pid
 - cat nohup.out 
 - cat Logs/*
 